### ISSUE TITLE
Issue :- Auto resolution changed to tablet size

### ISSUE THREAD

**Issue by VishnuSuresh2000** [RE800T/RALegacy_kernel_sdm439#2]
After flashing the new RALegancy kernel V8 for redmi 8 the resolution of the screen scaled to tablet like display ( which display appears to tablet like resolution)

**Comment by RE800T** [comment]
I am sorry for the inconvenience caused. The screen resolution (360) must be re-set in the developer settings (Minimum width) or in the display settings. Depends on ROM
